---
# tasks file for sensors
- name: Stop
  command: chdir=pollicino ./stop.sh
  register: output


# tasks file for sensors
- name: Start
  command: chdir=pollicino ./sensors.sh -b broker
  register: output

# tasks file for sensors
- name: State
  command: chdir=pollicino ./state.sh
  register: output
- debug: msg="{{ output.stdout_lines }}"
- debug: msg="{{ output.stderr_lines }}"
