- name: Clone/Update Pollicino repository
  git:
    repo: git@github.com:enzomar/pollicino.git
    dest: pollicino
    update: yes
    clone: yes
    force: yes

- name: Setup environment (if needed)
  command: chdir=pollicino ./setup.sh
  register: output

- debug: msg="{{ output.stdout_lines }}"
- debug: msg="{{ output.stderr_lines }}"

