- name: Clone/Update Pollicino repository
  git:
    repo: git@github.com:enzomar/pollicino.git
    dest: pollicino
    update: yes
    clone: yes
    force: yes

- name: Setup environment (if needed)
  command: chdir=pollicino ./setup.sh
  register: output
  args: 
    creates: venv

- debug: msg="{{ output.stdout }}"

- debug: msg="{{ output.stderr }}"