pollicino:
  sensors:
    '2':
      type: meteo
      pin_input: 24
      polling_seconds: 4
    '3':
      type: humidity
      pin_input: 24
      polling_seconds: 4
    '4':
      type: temperature
      pin_input: 24
      polling_seconds: 4
  