version: "3.9"
services:
  ctrl:
    build: .
    container_name: "ctrl"
    tty: true
    hostname: ctrl
    volumes:
      - ~/.ssh:/root/.ssh:ro

  broker:
    build: .
    container_name: "broker"
    tty: true
    hostname: broker

    volumes:
      - ~/.ssh:/root/.ssh:ro
    ports:
      - 1883:1883
      - 9001:9001

  sensor-a:
    build: .
    container_name: "sensor-a"
    tty: true
    hostname: sensor-a
    volumes:
      - ~/.ssh:/root/.ssh:ro


  sensor-b:
    build: .
    container_name: "sensor-b"
    tty: true
    hostname: sensor-b
    volumes: 
      - ~/.ssh:/root/.ssh:ro

  sensor-c:
    build: .
    container_name: "sensor-c"
    tty: true
    hostname: sensor-c
    volumes:
      - ~/.ssh:/root/.ssh:ro

  servo-a:
    build: .
    container_name: "servo-a"
    tty: true
    hostname: servo-a
    volumes:
      - ~/.ssh:/root/.ssh:ro

  servo-b:
    build: .
    container_name: "servo-b"
    tty: true
    hostname: servo-b
    volumes:
      - ~/.ssh:/root/.ssh:ro
