version: "3.9"
services:
  ctrl:
    build: .
    container_name: "ctrl"
    tty: true
    volumes:
      - ~/.ssh:/root/.ssh:ro

  broker:
    build: .
    container_name: "broker"
    tty: true
    volumes:
      - ~/.ssh:/root/.ssh:ro
    ports:
      - 1883:1883

  sensor_a:
    build: .
    container_name: "sensor-a"
    tty: true
    volumes:
      - ~/.ssh:/root/.ssh:ro


  sensor_b:
    build: .
    container_name: "sensor-b"
    tty: true
    volumes:
      - ~/.ssh:/root/.ssh:ro

  sensor_c:
    build: .
    container_name: "sensor-c"
    tty: true
    volumes:
      - ~/.ssh:/root/.ssh:ro

  servo_a:
    build: .
    container_name: "servo-a"
    tty: true
    volumes:
      - ~/.ssh:/root/.ssh:ro

  servo_b:
    build: .
    container_name: "servo-b"
    tty: true
    volumes:
      - ~/.ssh:/root/.ssh:ro
